export interface DemoProduct {
  id: string;
  name: string;
  handle: string;
  description: string;
  product_type: string;
  price: number;
  images: string[];
  tags: string[];
  status: string;
  sku?: string;
  has_variants?: boolean;
  inventory_qty?: number;
  variants?: Array<{
    id: string;
    title: string;
    option1?: string;
    price: number;
    inventory_qty?: number;
    position?: number;
    sku?: string;
  }>;
}

export const demoProducts: DemoProduct[] = [
  {
    id: 'demo-1',
    name: 'Aurora Smart Lamp',
    handle: 'aurora-smart-lamp',
    description: 'A compact smart lamp with warm ambient settings for any room.',
    product_type: 'Home',
    price: 6900,
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured', 'sale'],
    status: 'active',
    sku: 'AUR-001',
    has_variants: false,
    inventory_qty: 12,
  },
  {
    id: 'demo-2',
    name: 'Pulse Headphones',
    handle: 'pulse-headphones',
    description: 'Wireless noise-cancelling headphones tuned for immersive sound.',
    product_type: 'Electronics',
    price: 14900,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'PUL-002',
    has_variants: false,
    inventory_qty: 8,
  },
  {
    id: 'demo-3',
    name: 'Edge Everyday Tote',
    handle: 'edge-everyday-tote',
    description: 'A versatile everyday tote built for work, travel, and daily essentials.',
    product_type: 'Fashion',
    price: 9900,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'EDG-003',
    has_variants: false,
    inventory_qty: 15,
  },
  {
    id: 'demo-4',
    name: 'Terra Ceramic Set',
    handle: 'terra-ceramic-set',
    description: 'Elegant ceramic serving pieces for modern dining and hosting.',
    product_type: 'Home',
    price: 8200,
    images: ['https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured', 'sale'],
    status: 'active',
    sku: 'TER-004',
    has_variants: false,
    inventory_qty: 10,
  },
  {
    id: 'demo-5',
    name: 'Nova Running Jacket',
    handle: 'nova-running-jacket',
    description: 'Weather-ready running jacket with breathable comfort and a clean silhouette.',
    product_type: 'Fashion',
    price: 11900,
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'NOVA-005',
    has_variants: true,
    inventory_qty: 9,
    variants: [
      { id: 'demo-5-s', title: 'Small', option1: 'S', price: 11900, inventory_qty: 4, position: 1, sku: 'NOVA-005-S' },
      { id: 'demo-5-m', title: 'Medium', option1: 'M', price: 11900, inventory_qty: 3, position: 2, sku: 'NOVA-005-M' },
      { id: 'demo-5-l', title: 'Large', option1: 'L', price: 11900, inventory_qty: 2, position: 3, sku: 'NOVA-005-L' },
    ],
  },
  {
    id: 'demo-6',
    name: 'Kilo Fitness Bottle',
    handle: 'kilo-fitness-bottle',
    description: 'Insulated hydration bottle made for active routines and home workouts.',
    product_type: 'Beauty',
    price: 3400,
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'KIL-006',
    has_variants: false,
    inventory_qty: 18,
  },
  {
    id: 'demo-7',
    name: 'Halo Desk Speaker',
    handle: 'halo-desk-speaker',
    description: 'Desk-friendly speaker with loud clarity and elegant soft-touch finish.',
    product_type: 'Electronics',
    price: 7600,
    images: ['https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured', 'sale'],
    status: 'active',
    sku: 'HAL-007',
    has_variants: false,
    inventory_qty: 13,
  },
  {
    id: 'demo-8',
    name: 'Velvet Linen Set',
    handle: 'velvet-linen-set',
    description: 'A breathable linen trio that brings softness and warmth into any room.',
    product_type: 'Home',
    price: 11500,
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80'],
    tags: ['sale'],
    status: 'active',
    sku: 'VEL-008',
    has_variants: false,
    inventory_qty: 7,
  },
  {
    id: 'demo-9',
    name: 'Orbit Travel Case',
    handle: 'orbit-travel-case',
    description: 'A premium carry case that keeps your essentials protected and organized.',
    product_type: 'Accessories',
    price: 6200,
    images: ['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'ORB-009',
    has_variants: false,
    inventory_qty: 14,
  },
  {
    id: 'demo-10',
    name: 'Mira Skin Serum',
    handle: 'mira-skin-serum',
    description: 'A rich daily skin serum crafted for hydration and visible glow.',
    product_type: 'Beauty',
    price: 8800,
    images: ['https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'MIR-010',
    has_variants: false,
    inventory_qty: 16,
  },
  {
    id: 'demo-11',
    name: 'Luna Aroma Diffuser',
    handle: 'luna-aroma-diffuser',
    description: 'A compact diffuser that fills your space with a calm, elegant scent profile.',
    product_type: 'Home',
    price: 7200,
    images: ['https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'LUN-011',
    has_variants: false,
    inventory_qty: 11,
  },
  {
    id: 'demo-12',
    name: 'Breeze Bluetooth Speaker',
    handle: 'breeze-bluetooth-speaker',
    description: 'Portable audio with balanced bass, clean mids, and a rich deep finish.',
    product_type: 'Electronics',
    price: 9800,
    images: ['https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'BRE-012',
    has_variants: false,
    inventory_qty: 14,
  },
  {
    id: 'demo-13',
    name: 'Horizon Sunglasses',
    handle: 'horizon-sunglasses',
    description: 'Lightweight, bold-frame shades built for everyday travel and style.',
    product_type: 'Accessories',
    price: 6500,
    images: ['https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=900&q=80'],
    tags: ['sale'],
    status: 'active',
    sku: 'HOR-013',
    has_variants: false,
    inventory_qty: 9,
  },
  {
    id: 'demo-14',
    name: 'Cedar Travel Mug',
    handle: 'cedar-travel-mug',
    description: 'A premium insulated mug designed for commutes, workdays, and mornings on the move.',
    product_type: 'Home',
    price: 4200,
    images: ['https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'CED-014',
    has_variants: false,
    inventory_qty: 22,
  },
  {
    id: 'demo-15',
    name: 'Sole Pace Sneakers',
    handle: 'sole-pace-sneakers',
    description: 'Everyday sneakers with supportive cushioning and a street-ready silhouette.',
    product_type: 'Fashion',
    price: 13200,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'SOL-015',
    has_variants: false,
    inventory_qty: 10,
  },
  {
    id: 'demo-16',
    name: 'Aster Knit Scarf',
    handle: 'aster-knit-scarf',
    description: 'Soft knit scarf with a refined texture that layers easily into any outfit.',
    product_type: 'Fashion',
    price: 4700,
    images: ['https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80'],
    tags: ['sale'],
    status: 'active',
    sku: 'AST-016',
    has_variants: false,
    inventory_qty: 17,
  },
  {
    id: 'demo-17',
    name: 'Dune Projector',
    handle: 'dune-projector',
    description: 'A portable mini projector that turns any room into a cinematic setup.',
    product_type: 'Electronics',
    price: 18900,
    images: ['https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'DUN-017',
    has_variants: false,
    inventory_qty: 6,
  },
  {
    id: 'demo-18',
    name: 'Cloud Pillow Set',
    handle: 'cloud-pillow-set',
    description: 'Soft, supportive pillows designed to elevate comfort in every room.',
    product_type: 'Home',
    price: 5800,
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80'],
    tags: ['sale'],
    status: 'active',
    sku: 'CLO-018',
    has_variants: false,
    inventory_qty: 13,
  },
  {
    id: 'demo-19',
    name: 'Petal Face Mist',
    handle: 'petal-face-mist',
    description: 'A refreshing hydrating spray to bring comfort and glow throughout the day.',
    product_type: 'Beauty',
    price: 3900,
    images: ['https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'PET-019',
    has_variants: false,
    inventory_qty: 19,
  },
  {
    id: 'demo-20',
    name: 'Crest Fitness Band',
    handle: 'crest-fitness-band',
    description: 'A sleek fitness tracker that helps you stay on pace with your wellness goals.',
    product_type: 'Electronics',
    price: 9100,
    images: ['https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'CRE-020',
    has_variants: false,
    inventory_qty: 12,
  },
  {
    id: 'demo-21',
    name: 'Marlow Leather Wallet',
    handle: 'marlow-leather-wallet',
    description: 'Minimal everyday wallet in premium leather with organized card storage.',
    product_type: 'Accessories',
    price: 7600,
    images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'MAR-021',
    has_variants: false,
    inventory_qty: 10,
  },
  {
    id: 'demo-22',
    name: 'Tide Cotton Hoodie',
    handle: 'tide-cotton-hoodie',
    description: 'A relaxed everyday hoodie with a smooth fit and easy layering feel.',
    product_type: 'Fashion',
    price: 10400,
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'TID-022',
    has_variants: true,
    inventory_qty: 8,
    variants: [
      { id: 'demo-22-s', title: 'Small', option1: 'S', price: 10400, inventory_qty: 3, position: 1, sku: 'TID-022-S' },
      { id: 'demo-22-m', title: 'Medium', option1: 'M', price: 10400, inventory_qty: 2, position: 2, sku: 'TID-022-M' },
      { id: 'demo-22-l', title: 'Large', option1: 'L', price: 10400, inventory_qty: 3, position: 3, sku: 'TID-022-L' },
    ],
  },
  {
    id: 'demo-23',
    name: 'Pine Book Stand',
    handle: 'pine-book-stand',
    description: 'A slim display stand that brings structure and style to your desk space.',
    product_type: 'Home',
    price: 5100,
    images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=900&q=80'],
    tags: ['sale'],
    status: 'active',
    sku: 'PIN-023',
    has_variants: false,
    inventory_qty: 15,
  },
  {
    id: 'demo-24',
    name: 'Zephyr Nail Kit',
    handle: 'zephyr-nail-kit',
    description: 'A curated nail care set with polished essentials for daily beauty routines.',
    product_type: 'Beauty',
    price: 4800,
    images: ['https://images.unsplash.com/photo-1600948836101-f9ffda59d250?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'ZEP-024',
    has_variants: false,
    inventory_qty: 18,
  },
  {
    id: 'demo-25',
    name: 'Atlas Camera Sling',
    handle: 'atlas-camera-sling',
    description: 'A minimalist sling bag for daily carry, urban travel, and light photography.',
    product_type: 'Accessories',
    price: 8700,
    images: ['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'ATL-025',
    has_variants: false,
    inventory_qty: 9,
  },
  {
    id: 'demo-26',
    name: 'Ridge Desk Lamp',
    handle: 'ridge-desk-lamp',
    description: 'Minimal desk lighting that brightens workspaces with a warm balanced glow.',
    product_type: 'Home',
    price: 6800,
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'RID-026',
    has_variants: false,
    inventory_qty: 12,
  },
  {
    id: 'demo-27',
    name: 'Aqua Bottle Duo',
    handle: 'aqua-bottle-duo',
    description: 'A matching bottle pair for hydration, travel, and daily active routines.',
    product_type: 'Accessories',
    price: 5400,
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=80'],
    tags: ['sale'],
    status: 'active',
    sku: 'AQU-027',
    has_variants: false,
    inventory_qty: 20,
  },
  {
    id: 'demo-28',
    name: 'Iris Compact Mirror',
    handle: 'iris-compact-mirror',
    description: 'Pocket-friendly beauty mirror with a polished finish and clean everyday look.',
    product_type: 'Beauty',
    price: 2600,
    images: ['https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'IRI-028',
    has_variants: false,
    inventory_qty: 28,
  },
  {
    id: 'demo-29',
    name: 'North Denim Jacket',
    handle: 'north-denim-jacket',
    description: 'A classic denim jacket with soft structure and timeless everyday styling.',
    product_type: 'Fashion',
    price: 12300,
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'NOR-029',
    has_variants: false,
    inventory_qty: 7,
  },
  {
    id: 'demo-30',
    name: 'Kora Ceramic Bowl',
    handle: 'kora-ceramic-bowl',
    description: 'Hand-finished ceramic bowl crafted for elevated serving and daily use.',
    product_type: 'Home',
    price: 4500,
    images: ['https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=900&q=80'],
    tags: ['sale'],
    status: 'active',
    sku: 'KOR-030',
    has_variants: false,
    inventory_qty: 16,
  },
  {
    id: 'demo-31',
    name: 'Nexa Wireless Charger',
    handle: 'nexa-wireless-charger',
    description: 'Fast, minimalist charging pad built to support your daily desk setup.',
    product_type: 'Electronics',
    price: 5600,
    images: ['https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'NEX-031',
    has_variants: false,
    inventory_qty: 15,
  },
  {
    id: 'demo-32',
    name: 'Lark Overnight Bag',
    handle: 'lark-overnight-bag',
    description: 'A structured overnight bag for short getaways and polished carry-on style.',
    product_type: 'Accessories',
    price: 10900,
    images: ['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'LAR-032',
    has_variants: false,
    inventory_qty: 8,
  },
  {
    id: 'demo-33',
    name: 'Riva Body Oil',
    handle: 'riva-body-oil',
    description: 'A nourishing body oil with a silky finish for smoother, softer skin.',
    product_type: 'Beauty',
    price: 6600,
    images: ['https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'RIV-033',
    has_variants: false,
    inventory_qty: 14,
  },
  {
    id: 'demo-34',
    name: 'Vela Weekend Tote',
    handle: 'vela-weekend-tote',
    description: 'A roomy tote in a clean silhouette, perfect for market runs and quick escapes.',
    product_type: 'Fashion',
    price: 9300,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80'],
    tags: ['sale'],
    status: 'active',
    sku: 'VEL-034',
    has_variants: false,
    inventory_qty: 12,
  },
  {
    id: 'demo-35',
    name: 'Fable Coffee Grinder',
    handle: 'fable-coffee-grinder',
    description: 'A sleek kitchen grinder that makes your daily brew feel a little more special.',
    product_type: 'Home',
    price: 8400,
    images: ['https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=900&q=80'],
    tags: ['featured'],
    status: 'active',
    sku: 'FAB-035',
    has_variants: false,
    inventory_qty: 11,
  },
];

export const demoCollections = [
  { id: 'demo-collection-1', title: 'New Arrivals', handle: 'new-arrivals', description: 'Fresh drops this season', is_visible: true, sort_order: 1 },
  { id: 'demo-collection-2', title: 'Sale', handle: 'sale', description: 'Special price savings', is_visible: true, sort_order: 2 },
  { id: 'demo-collection-3', title: 'Electronics', handle: 'electronics', description: 'Smart devices and accessories', is_visible: true, sort_order: 3 },
  { id: 'demo-collection-4', title: 'Fashion', handle: 'fashion', description: 'Modern pieces with everyday style', is_visible: true, sort_order: 4 },
  { id: 'demo-collection-5', title: 'Home', handle: 'home', description: 'Clean home essentials', is_visible: true, sort_order: 5 },
];

export const demoCollectionMap: Record<string, string[]> = {
  'new-arrivals': ['demo-1', 'demo-2', 'demo-3', 'demo-5', 'demo-11', 'demo-12', 'demo-13', 'demo-17'],
  'sale': ['demo-1', 'demo-4', 'demo-6', 'demo-13', 'demo-16', 'demo-18', 'demo-27', 'demo-30', 'demo-34'],
  electronics: ['demo-2', 'demo-7', 'demo-12', 'demo-17', 'demo-20', 'demo-31'],
  fashion: ['demo-3', 'demo-5', 'demo-15', 'demo-16', 'demo-22', 'demo-29', 'demo-34'],
  home: ['demo-1', 'demo-4', 'demo-8', 'demo-11', 'demo-14', 'demo-18', 'demo-23', 'demo-26', 'demo-30', 'demo-35'],
};

export const resolveDemoProduct = (idOrHandle: string) => {
  return demoProducts.find((product) => product.id === idOrHandle || product.handle === idOrHandle) || null;
};

export const resolveDemoProductsByIds = (ids: string[]) => {
  return demoProducts.filter((product) => ids.includes(product.id));
};

export const resolveDemoCollectionProducts = (handle: string) => {
  return resolveDemoProductsByIds(demoCollectionMap[handle] || []);
};
